language: 
    - python

services:
    - postgresql

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: "2.7"
    - os: osx
      osx_image: xcode6.4
      sudo: false
      language: generic

before_install:
    - git clone https://github.com/llvm-mirror/clang.git ~/llvm\
    - chmod a+x ~/llvm/tools/scan-build-py/bin/intercept-build;
    - export PATH=~/llvm/tools/scan-build-py/bin:$PATH;
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update;                        fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python;                fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install thrift;                fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen;               fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install coreutils;             fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl http://llvm.org/releases/3.7.0/clang+llvm-3.7.0-x86_64-apple-darwin.tar.xz -o clang+llvm-3.7.0-x86_64-apple-darwin.tar.xz; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar xf clang+llvm-3.7.0-x86_64-apple-darwin.tar.xz -C ~/; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=~/clang+llvm-3.7.0-x86_64-apple-darwin/bin/:$PATH; fi

install:
    - pip install -r ./.ci/python_requirements
    - pip install nose
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PG_DATA=$(brew --prefix)/var/postgres; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s postgres && psql -c 'create database travis_ci_test;' -U postgres && cat postgres.log; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise
        packages:
            - doxygen
            - libpq-dev
            - clang-3.7
            - libc6-dev-i386
            - gcc-multilib
            - thrift-compiler

    postgresql: "9.3"

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./change_clang_version_for_osx.py;                    fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./change_clang_version.py;                          fi

    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . tests/test_env_setup_osx.sh;                        fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . tests/test_env_setup_linux.sh;                    fi

    - ./build_package.py -o $TEST_CODECHECKER_PACKAGE_DIR -v

    - export TEST_USE_POSTGRESQL=false
    - unset CODECHECKER_DB_DRIVER
    - nosetests tests/test_packages/

    - export TEST_USE_POSTGRESQL=true
    - export TEST_DBUSERNAME="postgres"
    - export TEST_DBPORT="5432"

    - export CODECHECKER_DB_DRIVER=psycopg2
    - nosetests tests/test_packages/functional/package_test/

    - export CODECHECKER_DB_DRIVER=pg8000
    - nosetests tests/test_packages/functional/package_test/
