language: 
    - python

services:
    - postgresql

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: "2.7"
      env: DATABASE=sqlite
    - os: linux
      sudo: required
      dist: trusty
      python: "2.7"
      env: DATABASE=psql_psycopg2
    - os: osx
      osx_image: xcode8
      sudo: false
      language: generic
      env: DATABASE=sqlite
    - os: osx
      osx_image: xcode8
      sudo: false
      language: generic
      env: DATABASE=psql_psycopg2

before_install:
    # Download macOS specific extra dependencies.
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git clone https://github.com/llvm-mirror/clang.git ~/llvm --branch master --single-branch --depth 1; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm@3.9; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install thrift@0.9; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/Cellar/thrift@0.9/0.9.3/bin:$PATH; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which thrift; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/opt/llvm@3.9/bin:$PATH; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PYTHONPATH=~/llvm/tools/scan-build-py/; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=~/llvm/tools/scan-build-py/bin:$PATH; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod a+x ~/llvm/tools/scan-build-py/bin/intercept-build; fi

    # Set the proper Clang versions early in the PATH.
    - export PATH=$HOME:$PATH
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then which clang; which clang-tidy; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which clang; ln -s $(which clang) $HOME/clang; fi

    # PostgreSQL is not started automatically on macOS.
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PG_DATA=$(brew --prefix)/var/postgres; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}; cat postgres.log; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cat postgres.log; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s postgres; fi

install:
    - pip install nose pep8
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install virtualenv; fi
    - psql -c 'create database codechecker_config;' -U postgres
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cat postgres.log; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - doxygen
            - gcc-multilib
            - libc6-dev-i386
            - libpq-dev
            - thrift-compiler
    postgresql: "9.3"

script:
    - make clean_travis
    - if [[ ! -z "$DATABASE" ]]; then make test_matrix_${DATABASE}; else make test; fi
    - make clean_travis
