sudo: required
dist: trusty

language: python

python:
    - "2.7"

before_install:
    - sudo add-apt-repository ppa:adrozdoff/llvm-backport -y
    - sudo apt-get update -q
    - sudo apt-get install clang-3.7 -y

install:
    - pip install -r ./.ci/python_requirements
    - pip install nose

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            #- llvm-toolchain-precise-3.7
            #- llvm-toolchain-precise
        packages:
            - doxygen
            - libpq-dev
            # - clang-3.7
            - libc6-dev-i386
            - gcc-multilib
            - thrift-compiler

    postgresql: "9.3"

script:
    - ./change_clang_version.py

    - . tests/test_env_setup.sh

    - ./build_package.py -o $TEST_CODECHECKER_PACKAGE_DIR -v

    - export TEST_USE_POSTGRESQL=false
    - unset CODECHECKER_DB_DRIVER
    - nosetests tests/test_packages/

    - export TEST_USE_POSTGRESQL=true
    - export TEST_DBUSERNAME="postgres"
    - export TEST_DBPORT="5432"

    - export CODECHECKER_DB_DRIVER=psycopg2
    - nosetests tests/test_packages/functional/package_test/

    - export CODECHECKER_DB_DRIVER=pg8000
    - nosetests tests/test_packages/functional/package_test/

    - ./tests/clean_tests.sh
