sudo: required
dist: trusty

language: python

python:
    - "2.7"

install:
    - pip install -r ./.ci/python_requirements

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise
        packages:
            - doxygen
            - libpq-dev
            - clang-3.6
            - libc6-dev-i386
            - gcc-multilib
            - thrift-compiler

    postgresql: "9.3"

script:
    - ./test_unit_test.py
    - ./build_package.py -o ./codechecker_package -v
    - ./test_package.py -p ./codechecker_package/CodeChecker -v stable --dbport 5432 --dbusername postgres
    - ./test_quickcheck.py -p ./codechecker_package/CodeChecker
