language: 
    - python

services:
  - postgresql

matrix:
  include:
    - os: linux
      name: "Analyzer test cases"
      sudo: required
      dist: xenial
      python: "2.7"
      env: CC_MODULE=analyzer
    - os: linux
      sudo: required
      dist: xenial
      python: "2.7"
      env: DATABASE=sqlite
    - os: linux
      sudo: required
      dist: xenial
      python: "2.7"
      env: DATABASE=psql_psycopg2
    - os: linux
      sudo: required
      dist: xenial
      python: "2.7"
      env: DATABASE=psql_pg8000
    - os: osx
      osx_image: xcode9.4
      name: "Analyzer test cases"
      sudo: false
      language: generic
      env: CC_MODULE=analyzer
    - os: osx
      osx_image: xcode9.4
      sudo: false
      language: generic
      env: DATABASE=sqlite
    - os: osx
      osx_image: xcode9.4
      sudo: false
      language: generic
      env:
        - DATABASE=psql_psycopg2
        - POSTGRESQL_VERSION=9.6
    - os: osx
      osx_image: xcode9.4
      sudo: false
      language: generic
      env:
        - DATABASE=psql_pg8000
        - POSTGRESQL_VERSION=9.6

before_install:
    # Download macOS specific extra dependencies.
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git clone https://github.com/llvm-mirror/clang.git ~/llvm --branch master --single-branch --depth 1; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm@7; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade boost; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install thrift@0.9; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/Cellar/thrift@0.9/0.9.3/bin:$PATH; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which thrift; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/opt/llvm/bin:$PATH; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PYTHONPATH=~/llvm/tools/scan-build-py/; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=~/llvm/tools/scan-build-py/bin:$PATH; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod a+x ~/llvm/tools/scan-build-py/bin/intercept-build; fi

    # Set the proper Clang versions early in the PATH.
    - export PATH=$HOME:$PATH
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which clang; ln -s $(which clang) $HOME/clang; fi

    # PostgreSQL is not started automatically on macOS.
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/var/postgres; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services start postgres; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then while ! pg_isready; do sleep 1; done; createuser -s postgres; fi

install:
    - pip install nose pycodestyle
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install virtualenv; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-7 100; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-7 100; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-7 100; fi
    # Check if the right clang and clang-tidy is used
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then update-alternatives --display clang; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then update-alternatives --display clang-tidy; fi

addons:
    apt:
        sources:
            - llvm-toolchain-xenial-7
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - doxygen
            - gcc-multilib
            - libc6-dev-i386
            - libpq-dev
            - thrift-compiler
            - clang-7
            - clang-tidy-7
    postgresql: "9.6"

script:
    - make clean_travis
    - make package
    - >
      if [[ "$CC_MODULE" = "analyzer" ]]; then
        make -C analyzer test_unit test_functional test_tu_collector;
        if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
          make -C analyzer test_build_logger
        fi
      elif [[ ! -z "$DATABASE" ]]; then
        make test_matrix_${DATABASE};
      else
        make test;
      fi
    - make clean_travis
