sudo: required
dist: trusty

language: python

python:
    - "2.7"

install:
    - pip install -r ./.ci/python_requirements
    - pip install nose

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise
        packages:
            - doxygen
            - libpq-dev
            - clang-3.7
            - libc6-dev-i386
            - gcc-multilib
            - thrift-compiler

    postgresql: "9.3"

script:
    - ./change_clang_version.py

    - . tests/test_env_setup.sh

    - ./build_package.py -o $TEST_CODECHECKER_PACKAGE_DIR -v

    - nosetests tests/test_packages/unit/

    - nosetests tests/test_packages/functional/quickcheck_test/

    - export TEST_USE_POSTGRESQL=true
    - export CODECHECKER_DB_DRIVER=psycopg2
    - nosetests tests/test_packages/functional/package_test/

    - export TEST_USE_POSTGRESQL=true
    - export CODECHECKER_DB_DRIVER=pg8000
    - nosetests tests/test_packages/functional/package_test/

    - export TEST_USE_POSTGRESQL=true
    - unset CODECHECKER_DB_DRIVER
    - nosetests tests/test_packages/functional/package_test/

    - export TEST_USE_POSTGRESQL=false
    - unset CODECHECKER_DB_DRIVER
    - nosetests tests/test_packages/functional/package_test/
